volumes:
  db_data:

services:
  database:
    image: mysql:9.2.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meli
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
